import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: ["./src/**/*.{js,ts,jsx,tsx,mdx}"],
  theme: {
    extend: {
      colors: {
        outline: "#70787d",
        "tertiary-fixed-dim": "#b4cad6",
        "secondary-fixed-dim": "#70d8c8",
        "on-background": "#191c1d",
        "inverse-on-surface": "#f0f1f2",
        "on-tertiary-fixed": "#071e27",
        "on-secondary-container": "#007165",
        "on-surface-variant": "#40484d",
        "on-secondary-fixed": "#00201c",
        "on-secondary-fixed-variant": "#005048",
        "on-surface": "#191c1d",
        "inverse-surface": "#2e3132",
        "on-tertiary-fixed-variant": "#354a53",
        surface: "#f8f9fa",
        "surface-bright": "#f8f9fa",
        "surface-container-low": "#f3f4f5",
        "surface-container-highest": "#e1e3e4",
        "on-primary": "#ffffff",
        "tertiary-fixed": "#cfe6f2",
        "error-container": "#ffdad6",
        "surface-container-high": "#e7e8e9",
        "surface-container": "#edeeef",
        secondary: "#006b5f",
        "surface-container-lowest": "#ffffff",
        "on-error": "#ffffff",
        primary: "#00475e",
        "secondary-container": "#8df5e4",
        "primary-fixed-dim": "#92cfee",
        "on-secondary": "#ffffff",
        "on-primary-fixed-variant": "#004d66",
        "on-primary-container": "#9bd7f7",
        "on-tertiary-container": "#bcd2de",
        "outline-variant": "#c0c8cd",
        error: "#ba1a1a",
        "surface-dim": "#d9dadb",
        "on-primary-fixed": "#001e2b",
        "on-tertiary": "#ffffff",
        "surface-variant": "#e1e3e4",
        "primary-fixed": "#c0e8ff",
        "primary-container": "#1a5f7a",
        "on-error-container": "#93000a",
        "secondary-fixed": "#8df5e4",
        "inverse-primary": "#92cfee",
        tertiary: "#2f444d",
        "tertiary-container": "#465b65",
        "surface-tint": "#236580",
        background: "#f8f9fa",
      },
      fontFamily: {
        headline: ["Manrope", "sans-serif"],
        body: ["Plus Jakarta Sans", "sans-serif"],
        label: ["Plus Jakarta Sans", "sans-serif"],
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1rem",
        "3xl": "1.5rem",
        full: "9999px",
      },
    },
  },
  plugins: [],
};

export default config;
